export default [
  {
    name: "Ace Diamonds",
    rank: 1,
    order: 12,
    suit: "diamonds",
    imgName: "1d",
  },
  {
    name: "2 Diamonds",
    rank: 2,
    order: 13,
    suit: "diamonds",
    imgName: "2d",
  },
  {
    name: "3 Diamonds",
    rank: 3,
    order: 1,
    suit: "diamonds",
    imgName: "3d",
  },
  {
    name: "4 Diamonds",
    rank: 4,
    order: 2,
    suit: "diamonds",
    imgName: "4d",
  },
  {
    name: "5 Diamonds",
    rank: 5,
    order: 3,
    suit: "diamonds",
    imgName: "5d",
  },
  {
    name: "6 Diamonds",
    rank: 6,
    order: 4,
    suit: "diamonds",
    imgName: "6d",
  },
  {
    name: "7 Diamonds",
    rank: 7,
    order: 5,
    suit: "diamonds",
    imgName: "7d",
  },
  {
    name: "8 Diamonds",
    rank: 8,
    order: 6,
    suit: "diamonds",
    imgName: "8d",
  },
  {
    name: "9 Diamonds",
    rank: 9,
    order: 7,
    suit: "diamonds",
    imgName: "9d",
  },
  {
    name: "10 Diamonds",
    rank: 10,
    order: 8,
    suit: "diamonds",
    imgName: "10d",
  },
  {
    name: "Jack Diamonds",
    rank: 11,
    order: 9,
    suit: "diamonds",
    imgName: "11d",
  },
  {
    name: "Queen Diamonds",
    rank: 12,
    order: 10,
    suit: "diamonds",
    imgName: "12d",
  },
  {
    name: "King Diamonds",
    rank: 13,
    order: 11,
    suit: "diamonds",
    imgName: "13d",
  },
  { name: "Ace Hearts", rank: 1, order: 12, suit: "hearts", imgName: "1h" },
  { name: "2 Hearts", rank: 2, order: 13, suit: "hearts", imgName: "2h" },
  { name: "3 Hearts", rank: 3, order: 1, suit: "hearts", imgName: "3h" },
  { name: "4 Hearts", rank: 4, order: 2, suit: "hearts", imgName: "4h" },
  { name: "5 Hearts", rank: 5, order: 3, suit: "hearts", imgName: "5h" },
  { name: "6 Hearts", rank: 6, order: 4, suit: "hearts", imgName: "6h" },
  { name: "7 Hearts", rank: 7, order: 5, suit: "hearts", imgName: "7h" },
  { name: "8 Hearts", rank: 8, order: 6, suit: "hearts", imgName: "8h" },
  { name: "9 Hearts", rank: 9, order: 7, suit: "hearts", imgName: "9h" },
  { name: "10 Hearts", rank: 10, order: 8, suit: "hearts", imgName: "10h" },
  {
    name: "Jack Hearts",
    rank: 11,
    order: 9,
    suit: "hearts",
    imgName: "11h",
  },
  {
    name: "Queen Hearts",
    rank: 12,
    order: 10,
    suit: "hearts",
    imgName: "12h",
  },
  {
    name: "King Hearts",
    rank: 13,
    order: 11,
    suit: "hearts",
    imgName: "13h",
  },
  { name: "Ace Clubs", rank: 1, order: 12, suit: "clubs", imgName: "1c" },
  { name: "2 Clubs", rank: 2, order: 13, suit: "clubs", imgName: "2c" },
  { name: "3 Clubs", rank: 3, order: 1, suit: "clubs", imgName: "3c" },
  { name: "4 Clubs", rank: 4, order: 2, suit: "clubs", imgName: "4c" },
  { name: "5 Clubs", rank: 5, order: 3, suit: "clubs", imgName: "5c" },
  { name: "6 Clubs", rank: 6, order: 4, suit: "clubs", imgName: "6c" },
  { name: "7 Clubs", rank: 7, order: 5, suit: "clubs", imgName: "7c" },
  { name: "8 Clubs", rank: 8, order: 6, suit: "clubs", imgName: "8c" },
  { name: "9 Clubs", rank: 9, order: 7, suit: "clubs", imgName: "9c" },
  { name: "10 Clubs", rank: 10, order: 8, suit: "clubs", imgName: "10c" },
  { name: "Jack Clubs", rank: 11, order: 9, suit: "clubs", imgName: "11c" },
  {
    name: "Queen Clubs",
    rank: 12,
    order: 10,
    suit: "clubs",
    imgName: "12c",
  },
  {
    name: "King Clubs",
    rank: 13,
    order: 11,
    suit: "clubs",
    imgName: "13c",
  },
  { name: "Ace Spades", rank: 1, order: 12, suit: "spades", imgName: "1s" },
  { name: "2 Spades", rank: 2, order: 13, suit: "spades", imgName: "2s" },
  { name: "3 Spades", rank: 3, order: 1, suit: "spades", imgName: "3s" },
  { name: "4 Spades", rank: 4, order: 2, suit: "spades", imgName: "4s" },
  { name: "5 Spades", rank: 5, order: 3, suit: "spades", imgName: "5s" },
  { name: "6 Spades", rank: 6, order: 4, suit: "spades", imgName: "6s" },
  { name: "7 Spades", rank: 7, order: 5, suit: "spades", imgName: "7s" },
  { name: "8 Spades", rank: 8, order: 6, suit: "spades", imgName: "8s" },
  { name: "9 Spades", rank: 9, order: 7, suit: "spades", imgName: "9s" },
  { name: "10 Spades", rank: 10, order: 8, suit: "spades", imgName: "10s" },
  {
    name: "Jack Spades",
    rank: 11,
    order: 9,
    suit: "spades",
    imgName: "11s",
  },
  {
    name: "Queen Spades",
    rank: 12,
    order: 10,
    suit: "spades",
    imgName: "12s",
  },
  {
    name: "King Spades",
    rank: 13,
    order: 11,
    suit: "spades",
    imgName: "13s",
  },
];
